[View in Colaboratory](https://colab.research.google.com/github/tanthanadon/TensorFlow_Beginner/blob/master/TensorFlow_MachineLearning_Chapter1.ipynb)

# **Declaring Tensors**

### Fixed tensors

In [0]:
import tensorflow as tf
import numpy as np
row_dim = 3
col_dim = 3

In [0]:
# Create a zero filled tensor
zero_tsr = tf.zeros([row_dim, col_dim])
# Create one filed tensor
ones_tsr = tf.ones([row_dim, col_dim])
# Create a constant filled tensor
constant_tsr = tf.constant([1, 2, 3])

### Tensors of similar shape

In [0]:
zeros_similar = tf.zeros_like(constant_tsr)
ones_similar = tf.ones_like(constant_tsr)

### Sequence tensors

In [0]:
# Define intervals with linspace()
linear_tsr = tf.linspace(start=0.0, stop=1.0, num=3)
# Sequence in range()
integer_seq_tsr = tf.range(start=6, limit=15, delta=3)

### Random Tensors

In [0]:
# Random numbers from a uniform distribution
randunif_tsr = tf.random_uniform([row_dim, col_dim], minval=0, maxval=1)
# Random numbers from a normal distribution
randnorm_tsr = tf.random_normal([row_dim, col_dim], mean=0.0, stddev=1.0)
# Random numbers from two standard deviations of the specified mean
runcnorm_tsr = tf.truncated_normal([row_dim, col_dim], mean=0.0, stddev=1.0)
# Random numbers from entries of arrays
##shuffled_output = tf.random_shuffle(input_tensor)
##copped_output = tf.random_crop(input_tensor, crop_size)

# Using Placeholders and Variables

### How to do it

In [0]:

my_var = tf.Variable(tf.zeros([2,3]))
sess = tf.Session()
initialize_op = tf.global_variables_initializer ()
sess.run(initialize_op)

In [0]:
sees = tf.Session()
x = tf.placeholder(tf.float32, shape=[2,2])
y = tf.identity(x)
x_vals = np.random.rand(2,2)
sees.run(y, feed_dict={x: x_vals})
# Note that sees.run(x, feed_dict={x: x_vals}) will result in a self referencing error
# There's more
# Create an operation in the graph that initializes all the variables we have
initializer_op = tf.global_variables_initializer ()
sess = tf.Session()
first_var = tf.Variable(tf.zeros([2,3]))
second_var = tf.Variable(tf.zeros_like(first_var))
# Depends on first_var
sess.run(second_var.initializer)

# Working with Matrix

In [0]:
import tensorflow as tf
# To launch the graph in a session
sess = tf.Session()

### Creating matrix

In [91]:
identity_matrix = tf.diag([1.0, 1.0, 1.0])
A = tf.truncated_normal([2, 3])
B = tf.fill([2,3], 5.0)
C = tf.random_uniform([3,2])
D = tf.convert_to_tensor(np.array([[1., 2., 3.],[-3., -7., -1.],[0., 5., -2.]]))
print(sess.run(identity_matrix))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [93]:
print(sess.run(A))

[[ 0.460683   -1.2345217  -0.00973095]
 [-1.3073646  -0.692911   -0.2369066 ]]


In [94]:
print(sess.run(B))

[[5. 5. 5.]
 [5. 5. 5.]]


In [96]:
print(sess.run(C))

[[0.01556957 0.81581295]
 [0.78334856 0.95753264]
 [0.57781315 0.8711661 ]]


In [97]:
print(sess.run(D))

[[ 1.  2.  3.]
 [-3. -7. -1.]
 [ 0.  5. -2.]]


### Addition and Subtraction

In [98]:
print(sees.run(A+B))

[[5.822312  3.3626842 6.03309  ]
 [6.0697136 4.4479737 3.609723 ]]


In [99]:
print(sess.run(B-B))

[[0. 0. 0.]
 [0. 0. 0.]]


In [100]:
# Multiplication
print(sess.run(tf.matmul(B, identity_matrix)))

[[5. 5. 5.]
 [5. 5. 5.]]


In [101]:
print(sees.run(tf.transpose(C)))

[[0.49589837 0.15733337 0.06570482]
 [0.42138326 0.3855697  0.02410007]]


In [102]:
# Determinant
print(sees.run(tf.matrix_determinant(D)))

-37.99999999999999


In [103]:
# Inverse
print(sess.run(tf.matrix_inverse(D)))

[[-0.5        -0.5        -0.5       ]
 [ 0.15789474  0.05263158  0.21052632]
 [ 0.39473684  0.13157895  0.02631579]]


In [104]:
# Decompositions
print(sees.run(tf.cholesky(identity_matrix)))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [106]:
# Eigenvalues and eigenvectors
print(sess.run(tf.self_adjoint_eig(D)))

(array([-10.65907521,  -0.22750691,   2.88658212]), array([[ 0.21749542,  0.63250104, -0.74339638],
       [ 0.84526515,  0.2587998 ,  0.46749277],
       [-0.4880805 ,  0.73004459,  0.47834331]]))


# Declaing Operations

In [0]:
import tensorflow as tf
sess = tf.Session()

In [92]:
from sklearn import datasets
iris = datasets.load_iris();
print(len(iris.data))

150


In [81]:
print(len(iris.target))

150


In [82]:
print(iris.target[0]) # Sepal lenght, Sepal width,Petal length, Petal width

0


In [83]:
print(set(iris.target)) # I. setosa, I. virginica, I. versicolor

{0, 1, 2}
